### ISSUE TITLE
changes to config.json

### ISSUE THREAD

**Issue by tomismrkolj** [brookmiles/freqtrade-stuff#2]
I saw you changed some parilist filters today for ftx and kraken. I am running this strat on binance dry. 3 weeks and almost 75% profit. Very good. 
I was running 25 volume pairs, single volume filter, precision filter, no spread filter and no performance filter.

Which of both configs do you suggest for binance? kraken or ftx?
Why have you lovered first volume list from 25 to 20, removed precison filter, added spreadfilter and performance filter at the end of second volume list?
Why is there a difference between second volume filters in ftx and kraken? One has refreshperiod and the other does not.
Tnx.

**Comment by brookmiles** [comment]
> I saw you changed some parilist filters today for ftx and kraken. I am running this strat on binance dry. 3 weeks and almost 75% profit. Very good.

Great!

> Which of both configs do you suggest for binance? kraken or ftx?

I have no idea, I haven't run the bot on binance.

> Why have you lovered first volume list from 25 to 20, removed precison filter, added spreadfilter and performance filter at the end of second volume list?

The precision filter was excluding a pair I wanted to trade, SC/USD, and since I don't use stoploss, it's not really necessary.  The other changes are experimentation.  I find that including too many pairs results in making many more bad trades.

> Why is there a difference between second volume filters in ftx and kraken? One has refreshperiod and the other does not.

No particular reason, I wrote them at different times.
